name: CI_CD_FW_TESTE

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  use-reusable-workflow:
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/reusable-build.yml@main
    with:
     build_configuration: Release
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
  deploy:
    needs: use-reusable-workflow
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/package-deploy.yml@main
    with:
     build_configuration: Release
    secrets: inherit